### PR TITLE
English fixes

### PR DESCRIPTION
**Pull request by remram44**
This changes "dragon's tooth" to "dragon tooth", which in French are respectively "la dent du dragon" and "la dent de dragon".

Also typo rules about spaces are different in French and English.

### CODE REVIEW

**Comment by agryson** [comment]
Hi, thanks for spotting the extra space!
However, for the possessive "s" on Dragon's Tooth, plant names in English that are by analogy typically  use the possessive "s".
Examples:
- [Lamb's Ears (a.k.a. rabbit's ears)](http://www.garden.org/plantguide/?q=show&id=3370)
- [Cat's Paw](http://www.calyxflowers.com/floral-library/content/cats-paw.aspx)

**Comment by remram44** [comment]
Good point, I guess it is better for the twist. Reverted!

**Comment by cgand** [comment]
On Tue, Jan 26, 2016 at 8:36 PM, Remi Rampin notifications@github.com
wrote:

> [en] No space before ":" in English

Warning, is typical in Chaosah type rules have spaces before :  (colon) and
… (ellipsis)

I mean that we now that before : and … should be not spaces, but in Chaosah
world is different.

Look at all episode titles, they are always:

Episode X : Title of episode

This should be uniformed for all titles for all languages for all episodes.

**Comment by agryson** [comment]
@remram44 is correct that technically in English print there should be no space before the colon.
@cgand is right that in other episodes, (particularly titles) a space has been used, but I have to admit this is more due to just feeling a space looks better in some circumstances, not following any rules! (Though in speech bubbles I generally try to respect the rules more)

So the choice is:
- "Correct" localisation (no space before) which we update on all previous episodes
- Stylistic use of a space for titles, not in speech bubbles (and of course check to ensure rule is applied in previous episodes)

What does everyone think? 
It would be good to decide quickly so that we have time to correct it "before print" this Friday.

**Comment by Willem3141** [comment]
About the space before a colon: in the Dutch translation we consistently don't use a space, in all episodes, since putting a space before a punctuation mark looks strange in Dutch.

> This should be uniformed for all titles for all languages for all episodes.

I think that consistency within a language is more important than unifying all languages. For example in French the space is obligatory (I think?) and there are even languages (for example Japanese) that do not use spaces at all.

@agryson Personally, I would omit the spaces, but because I'm not a native English speaker you should take my opinion with a grain of salt :wink:

**Comment by agryson** [comment]
My personal thoughts: 
For consistency, it's probably better to use "proper" rules and thus to accept and merge this pull request. I (or someone else) can then go back to previous episodes for corrections.

In some cases, with the Lavi font, this means the colon will sometimes be "eaten" by the preceding character, but I think it's the most consistent choice.

**Comment by agryson** [comment]
@willem3141 English is generally much more flexible with punctuation rules, what with Americans and British speakers using commas differently (I use US English for P&C because it's more international, even though I'm a British English speaker.)
But you're absolutely right that consistency is more important! :-)

**Comment by cgand** [comment]
On Wed, Jan 27, 2016 at 8:43 AM, Alex Gryson notifications@github.com
wrote:

> Stylistic use of a space for titles, not in speech bubbles (and of course
> check to ensure rule is applied in previous episodes)

Agree with above:
- Episode NN : Title of episode
- No space before in bubbles

otherwise we have to check hundres titles.

**Comment by agryson** [comment]
Well, even if we define a specific "style guide", we'd still need to go through all old episodes to make sure it's respected. But since technically this is my "mistake" I'll take care of going through them all :-P.

**Comment by Deevad** [comment]
Ok. Let's fix the Chaosah typographic rules once for all :-) First fix to-do is on my side: the core problem is in Lavi font (too weak space before colon, maybe semi-colon too). I had to workaround with an empty space before colon, and this is not correct. I'm the origin of the mistake :D 

I just reported it here:
https://github.com/Deevad/peppercarrot_fonts/issues/4

Then I'll find a magic sed line with regular expression to batch fix all.
It's a very delicate move: it will requiers to re-render around 7000 pages in low-res and high res, and re-upload GB of datas. So, maybe this big fix will happen post release of ep14.

**Comment by agryson** [comment]
I think it should definitely happen _after_ Episode 14, and sed or not, a manual check of panels will be necessary. I'll just make a pot of coffee on Sunday and go through them (I've seen sed do strange things sometimes!)
This should only affect English, no?

**Comment by remram44** [comment]
I'm sorry my PR devolved into a nitpick, I didn't mean to cause such a commotion ;)

I can definitely help go through them if you decide to fix the colons (definitely not a big deal if you don't feel it's worth it).

**Comment by Deevad** [comment]
No problem @remram44  ;-)
+1 @agryson , yes English will be a priority. I'll try to script something to 'batch' it, there is too much files. (cover and titles have pattern in filename for a quick search ; Lavi is easy to 'grep', then 'sed' ... it should work).

**Comment by agryson** [comment]
OK, well we can already start by merging this request then, letting you get back to work on Episode 14 @Deevad , and after publication we can figure out the best way to fix the rest.

**Comment by Deevad** [comment]
2016-01-27_screenshot_002
^ a screenshot rendering. Maybe the spacing issue with this colon on Lavi is just in my mind and not dramatic. What do you think about it?

**Comment by cgand** [comment]
Most letters are rather italics, comma not.
_Anyway I like Episode ## : Title Of Episode_

**Comment by Willem3141** [comment]
@Deevad Honestly, I don't think the spacing before the colon is too small. Perhaps it might be a tiny bit wider, but to my eye the current situation is fine as well :smile:

**Comment by Deevad** [comment]
Haha, nice. So the fix of the spacing before colon can be done without Lavi modified.
But I'll modify a bit Lavi anyway for the future; @cgand is right ; ( "Most letters are rather italics, comma not." ).

**Comment by agryson** [comment]
Yeah, it looks fine to me too, like I said originally, it was really just a matter of personal taste, I should have thought to ask about it earlier maybe!

**Pull request merged**
